### ISSUE TITLE
扫描界面有些小问题

### ISSUE THREAD

**Issue by Azuredrop** [leyan95/qrcode_scanner#11]
调用scan()打开的扫描界面，左上角的返回按钮和右上角的图片按钮无法有效触发。
在实体机测试时，返回按钮不太好触发（可以稍微加大点？或是调大点，点击有效区）
图片按钮则似乎完全无效。。。

**Comment by leyan95** [comment]
@Azuredrop 好的，扫描界面右上角的图片选择功能还没加，暂时只能调用 `scanner.scanPhoto()` 方法扫描图片，我尽快修改😋。
