### ISSUE TITLE
The plugin `qrscan` uses a deprecated version of the Android embedding.

### ISSUE THREAD

**Issue by eslam733** [leyan95/qrcode_scanner#125]
![Screenshot_1](https://user-images.githubusercontent.com/43525248/139738168-b15ede9f-68b6-4ee5-b813-e3537f97a606.png)

**Comment by eslam733** [comment]
how can solve this problem

**Comment by t-k-c** [comment]
There's nothing you can do for now. But anyway, it's just a warning. We hope an update for this plugin comes supporting Android V2 embedding before the deprecated APIs are totally removed from the upcoming flutter versions

**Comment by tayfunuyar** [comment]
you can use https://pub.dev/packages/barcode_scan2
