### ISSUE TITLE
Unable to build application 'Could not resolve com.github.leyan95:android-zxingLibrary:0.1.2-PRE'

### ISSUE THREAD

**Issue by lowwailum123** [leyan95/qrcode_scanner#127]
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:processDebugResources'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.github.leyan95:android-zxingLibrary:0.1.2-PRE.
     Required by:
         project :app > project :qrscan
      > Could not resolve com.github.leyan95:android-zxingLibrary:0.1.2-PRE.
         > Could not get resource 'https://google.bintray.com/exoplayer/com/github/leyan95/android-zxingLibrary/0.1.2-PRE/android-zxingLibrary-0.1.2-PRE.pom'.
            > Could not GET 'https://google.bintray.com/exoplayer/com/github/leyan95/android-zxingLibrary/0.1.2-PRE/android-zxingLibrary-0.1.2-PRE.pom'. Received status code 502 from server: Bad Gateway

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s

**Comment by lowwailum123** [comment]
After further investigations, it is likely caused by the shutting down of jCenter which the bintray is hosted on at May 1st, 2021. The author will need to change the repository where he host it on. Though it only happened to me at December 1st, 2021 so I can't be too sure.

**Comment by mrdavidhsieh** [comment]
Same issue here, looks like it's a server problem, can't download necessary file from the remote address, pls help to fix, thanks.

**Comment by cedos10** [comment]
same issue to me also,but i,m using the latest version 0.3.2 Null safety  .what about downgrading it?
couldn.t be  temporary solution??

**Comment by PJohNSK** [comment]
Is there any fix for this issue? I'm using the latest version 0.3.2

**Comment by edbertproject** [comment]
downgrading does not solve the problem, I'm temporarily switching to another library. Still looking permanent solution for issue

**Comment by leyan95** [comment]
@lowwailum123 
Add it in your root build.gradle at the end of repositories:
```
allprojects {
		repositories {
			...
			maven { url 'https://jitpack.io' }
		}
	}
```
