### ISSUE TITLE
Scan on streaming camera

### ISSUE THREAD

**Issue by nanox77** [leyan95/qrcode_scanner#13]
Hi, Can I apply qrcode_scanner just when I'm streaming from camera?.

I need do the following code, for example:

```
cameraController.startImageStream((CameraImage availableImage) {
    _qrScan(availableImage);
});
```

I noticed when I execute `scan()`, this method open the camera. Can I apply just code processing given an CameraImage?

Thank you!

**Comment by leyan95** [comment]
@nanox77 Hi! I'm glad to receive from you. 
    It's only apply canning image witch in your albums so far.
    You can upgrade to the latest version and you can scanning image witch in your albums, call `scanPhoto()`,
    In the next version, I'll add a method called `Future<String> fromStream(Uint8List stream)` If you have a strong need for this method😊

**Comment by leyan95** [comment]
@nanox77 upgrade to ^0.2.16 and try the following code:
```dart
    File file = await ImagePicker.pickImage(source: ImageSource.camera);
    await ImageGallerySaver.saveImage(file.readAsBytesSync());
    String path = file.path;
    String barcode = await scanner.scanPath(path);
```
