### ISSUE TITLE
为什么我导入依赖 项目就运行不起来饿了

### ISSUE THREAD

**Issue by IT-ACMD** [leyan95/qrcode_scanner#16]
write  qrscan: ^0.2.17

An error has occurred    "Gradle task assembleDebug failed with exit code 1"

why?

**Comment by IT-ACMD** [comment]
我导入依赖  qrscan: ^0.2.17
项目就运行不起来了 报"Gradle task assembleDebug failed with exit code 1"
但是当我把版本降到 qrscan:^0.1.9
又可以正常运行了
为什么？是高版本的需要注意什么问题么？还是需要配置什么？

**Comment by leyan95** [comment]
@IT-ACMD 尝试运行下面的命令试一下
```shell
flutter clean
flutter run
```
或者 下载这个项目尝试运行这个插件里的demo看看能不能起来。
