### ISSUE TITLE
Unable to find activity 'com.shinow.qrscan.SecondActivity'

### ISSUE THREAD

**Issue by digibum** [leyan95/qrcode_scanner#17]
When calling `String barcode = await scanner.scan();` I get this error:

> PlatformException (PlatformException(error, Unable to find explicit activity class {hsi.alarm.prevozi/com.shinow.qrscan.SecondActivity}; have you declared this activity in your AndroidManifest.xml?, null))

When calling `String cameraScanResult = await scanner.scanPath(imagePath);` future newer returns result.

Using latest versions, AndroidX and added required user-permissions. What am I dooing wrong?

**Comment by leyan95** [comment]
@digibum 
Hi:

Try to run commands:
```shell
    flutter clean
    flutter run
```

**Comment by digibum** [comment]
> @digibum
> Hi:
> 
> Try to run commands:
> 
> ```shell
>     flutter clean
>     flutter run
> ```

Awesome, this solved my problem. Thank you!
