### ISSUE TITLE
can't run on IOS

### ISSUE THREAD

**Issue by wxbhlj** [leyan95/qrcode_scanner#2]
Unable to determine Swift version for the following pods:

qrscan does not specify a Swift version and none of the targets Runner integrating it have the "SWIFT_VERSION" attributeset. Please contact the author or set the "SWIFT_VERSION" attribute in at least one of the targets that integrate this pod.

**Comment by leyan95** [comment]
@wxbhlj Sorry, this plug-in does not support IOS system for the time being.
