### ISSUE TITLE
Disable File Picker button in QR Scan Screen

### ISSUE THREAD

**Issue by jamshaid120** [leyan95/qrcode_scanner#46]
How can I disable/remove the File picker button given in the QRScan screen?
There is no way defined for it.

**Comment by cviali** [comment]
You can modify the plugin's source code by going through Flutter Plugins(check the most bottom items on your android studio project tree) > qrscan > android > src.main > res > layout > activity_second.xml and add android:visibility="invisible" to LinearLayout with id choose_photo

**Comment by jamshaid120** [comment]
Thanks for your reply. I'll try it out
