### ISSUE TITLE
Build failed with qrscan

### ISSUE THREAD

**Issue by WangMiaoGit** [leyan95/qrcode_scanner#7]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':qrscan'.
> Failed to notify project evaluation listener.
   > java.lang.AbstractMethodError (no error message)

**Comment by leyan95** [comment]
@WangMiaoGit  主要是由于Gradle版本导致的问题，确认android目录下的build.gradle文件里buildscript 节点下依赖 是gradle:3.2.1
```
dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
        ... ...
    }
```

**Comment by WangMiaoGit** [comment]
这个和androidx没有关系是吧

**Comment by leyan95** [comment]
@WangMiaoGit 有关系 升级到0.2.12试试。
