### ISSUE TITLE
This plugin can not used by an Application of Android X。

### ISSUE THREAD

**Issue by Azuredrop** [leyan95/qrcode_scanner#8]
import android.support.v4.content.ContextCompat;
import android.support.v4.app.ActivityCompat;
import android.support.v7.app.AppCompatActivity;

Hello, 因为Androidx和Android support库不能共存问题导致不能直接引用插件使用，能不能把插件 Migrate to AndroidX，不然只能修改了在本地引用了。

**Comment by leyan95** [comment]
@Azuredrop 升级到0.2.12试试。

**Comment by Azuredrop** [comment]
![image](https://user-images.githubusercontent.com/5195346/63262760-6aea7780-c2b9-11e9-8fdc-fe3f137042c3.png)
😭文件没变啊，我本地升级后是这样的
![image](https://user-images.githubusercontent.com/5195346/63262839-99685280-c2b9-11e9-87ef-5aa033186f24.png)

**Comment by leyan95** [comment]
@Azuredrop  来吧老铁 接着升级 0.2.13

**Comment by Azuredrop** [comment]
@leyan95 可以了👍  目前没发现什么问题，虽然android下build时会报错，但不影响使用
![image](https://user-images.githubusercontent.com/5195346/63314430-336fdf80-c33a-11e9-9d93-294bdf5452fd.png)
![image](https://user-images.githubusercontent.com/5195346/63314438-3c60b100-c33a-11e9-995d-b728c3bc5119.png)

**Comment by leyan95** [comment]
@Azuredrop androidStudio 装一个 Kotlin 插件试试，或者更换一下版本。😄
