### ISSUE TITLE
There was an error when selecting image scanning code in the album. Could you please solve it?

### ISSUE THREAD

**Issue by Tom0115** [leyan95/qrcode_scanner#83]
error messages：

E/BitmapFactory( 7226): Unable to decode stream: java.io.FileNotFoundException: /storage/emulated/0/Pictures/WeiXin/mmexport1608781083585.png: open failed: EACCES (Permission denied)
W/System.err( 7226): java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
W/System.err( 7226): 	at com.uuzuche.lib_zxing.camera.BitmapLuminanceSource.<init>(BitmapLuminanceSource.java:16)
W/System.err( 7226): 	at com.uuzuche.lib_zxing.activity.CodeUtils.analyzeBitmap(CodeUtils.java:86)
W/System.err( 7226): 	at com.uuzuche.lib_zxing.activity.CodeUtils.analyzeBitmap(CodeUtils.java:62)
W/System.err( 7226): 	at com.shinow.qrscan.QrscanPlugin.onActivityResult(QrscanPlugin.java:107)
W/System.err( 7226): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEnginePluginRegistry.java:691)
W/System.err( 7226): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onActivityResult(FlutterEnginePluginRegistry.java:378)
W/System.err( 7226): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:625)
W/System.err( 7226): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:583)
W/System.err( 7226): 	at android.app.Activity.dispatchActivityResult(Activity.java:8300)
W/System.err( 7226): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5353)
W/System.err( 7226): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5401)
W/System.err( 7226): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
W/System.err( 7226): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
W/System.err( 7226): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
W/System.err( 7226): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
W/System.err( 7226): 	at android.os.Handler.dispatchMessage(Handler.java:107)
W/System.err( 7226): 	at android.os.Looper.loop(Looper.java:237)
W/System.err( 7226): 	at android.app.ActivityThread.main(ActivityThread.java:8167)
W/System.err( 7226): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 7226): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
W/System.err( 7226): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

**Comment by Sheharyar566** [comment]
Tom can you please tell why you closed the issue? I'm facing the same issue

**Comment by pokapow** [comment]
Same problem here, only on emulator in debug, can't give read right only for this package...
