### ISSUE TITLE
Support Null-Safety

### ISSUE THREAD

**Issue by joleaf** [leyan95/qrcode_scanner#99]
### 🚀 Feature Requests
add null-safety support

Flutter stable version is 2.0.0, support null-safety

**Comment by lucaslannes** [comment]
@joleaf, I made a pull request that enables null safety support. Check this out, please #102 😁

**Comment by joleaf** [comment]
@leyan95 can you check this merge request? :)

**Comment by leyan95** [comment]
@lucaslannes @joleaf  Thank you for your contributions 😁

**Comment by lucaslannes** [comment]
@leyan95, thanks to accept my pull request! But I think that you accidentally made a mistake, because in the pubspec.yaml the lower Dart SDK constraint is setted to 2.7.0. The correct constraints (according to the Dart guide, [see here](https://dart.dev/null-safety/migration-guide)), is 2.12.0 😄

**Comment by leyan95** [comment]
hahah...
@lucaslannes Thank you for your correction👍
